# Generated by Django 5.0.4 on 2024-04-24 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('time_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeProfessional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='agenda.client')),
                ('professional', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='agenda.professional')),
                ('service', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='agenda.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='type_professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.typeprofessional'),
        ),
        migrations.AddField(
            model_name='professional',
            name='type_professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.typeprofessional'),
        ),
    ]
