# Generated by Django 5.0.4 on 2024-04-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_events_professional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='name',
        ),
    ]
