# Generated by Django 5.0.4 on 2024-04-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_events_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioscomcamposadicionais',
            name='type_professional',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type_professional',
        ),
        migrations.RemoveField(
            model_name='usuarioscomcamposadicionais',
            name='user',
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('services', models.ManyToManyField(related_name='services', to='agenda.service')),
            ],
        ),
        migrations.DeleteModel(
            name='TypeProfessional',
        ),
        migrations.DeleteModel(
            name='UsuariosComCamposAdicionais',
        ),
    ]
