# Generated by Django 5.0.4 on 2024-05-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_events_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('E', 'Em andamento'), ('F', 'Faltou'), ('C', 'Cancelado'), ('R', 'Realizado')], default='P', max_length=1),
        ),
    ]
