# Generated by Django 5.0.4 on 2024-05-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_events_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('E', 'Em andamento'), ('F', 'Faltou'), ('C', 'Cancelado'), ('R', 'Realizado'), ('B', 'Bloqueado')], default='P', max_length=1),
        ),
    ]
